//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/Prefabs/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""RightXRController"",
            ""id"": ""ac9a0513-6003-4f5a-a0e6-f7e8ed694b2d"",
            ""actions"": [
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""45f8c144-f4eb-4343-92b3-f6d075dd0808"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""21fd79ee-acff-408f-87e3-e52b476a4a12"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1fbb4d1a-faf3-4cfc-9d51-7b7cde30090d"",
                    ""path"": ""<XRController>{RightHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4aa6f707-93a7-49e5-ba02-7147ea9049bc"",
                    ""path"": ""<XRController>{RightHand}/pointerRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""LeftXRController"",
            ""id"": ""e7605dfd-98ae-425c-8708-aa604d9549af"",
            ""actions"": [
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""ee292256-98ff-484c-b58b-6bc5a47f6cbb"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""3891b01b-36be-48d0-aae1-9faa81e4f63e"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4e72a383-a470-4e9f-8054-e27e4ab5554a"",
                    ""path"": ""<XRController>{LeftHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8bfb158-d247-4555-9a5c-103673bd2efa"",
                    ""path"": ""<XRController>{LeftHand}/pointerRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // RightXRController
        m_RightXRController = asset.FindActionMap("RightXRController", throwIfNotFound: true);
        m_RightXRController_Position = m_RightXRController.FindAction("Position", throwIfNotFound: true);
        m_RightXRController_Rotation = m_RightXRController.FindAction("Rotation", throwIfNotFound: true);
        // LeftXRController
        m_LeftXRController = asset.FindActionMap("LeftXRController", throwIfNotFound: true);
        m_LeftXRController_Position = m_LeftXRController.FindAction("Position", throwIfNotFound: true);
        m_LeftXRController_Rotation = m_LeftXRController.FindAction("Rotation", throwIfNotFound: true);
    }

    ~@PlayerInput()
    {
        UnityEngine.Debug.Assert(!m_RightXRController.enabled, "This will cause a leak and performance issues, PlayerInput.RightXRController.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_LeftXRController.enabled, "This will cause a leak and performance issues, PlayerInput.LeftXRController.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // RightXRController
    private readonly InputActionMap m_RightXRController;
    private List<IRightXRControllerActions> m_RightXRControllerActionsCallbackInterfaces = new List<IRightXRControllerActions>();
    private readonly InputAction m_RightXRController_Position;
    private readonly InputAction m_RightXRController_Rotation;
    public struct RightXRControllerActions
    {
        private @PlayerInput m_Wrapper;
        public RightXRControllerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Position => m_Wrapper.m_RightXRController_Position;
        public InputAction @Rotation => m_Wrapper.m_RightXRController_Rotation;
        public InputActionMap Get() { return m_Wrapper.m_RightXRController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RightXRControllerActions set) { return set.Get(); }
        public void AddCallbacks(IRightXRControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_RightXRControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RightXRControllerActionsCallbackInterfaces.Add(instance);
            @Position.started += instance.OnPosition;
            @Position.performed += instance.OnPosition;
            @Position.canceled += instance.OnPosition;
            @Rotation.started += instance.OnRotation;
            @Rotation.performed += instance.OnRotation;
            @Rotation.canceled += instance.OnRotation;
        }

        private void UnregisterCallbacks(IRightXRControllerActions instance)
        {
            @Position.started -= instance.OnPosition;
            @Position.performed -= instance.OnPosition;
            @Position.canceled -= instance.OnPosition;
            @Rotation.started -= instance.OnRotation;
            @Rotation.performed -= instance.OnRotation;
            @Rotation.canceled -= instance.OnRotation;
        }

        public void RemoveCallbacks(IRightXRControllerActions instance)
        {
            if (m_Wrapper.m_RightXRControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRightXRControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_RightXRControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RightXRControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RightXRControllerActions @RightXRController => new RightXRControllerActions(this);

    // LeftXRController
    private readonly InputActionMap m_LeftXRController;
    private List<ILeftXRControllerActions> m_LeftXRControllerActionsCallbackInterfaces = new List<ILeftXRControllerActions>();
    private readonly InputAction m_LeftXRController_Position;
    private readonly InputAction m_LeftXRController_Rotation;
    public struct LeftXRControllerActions
    {
        private @PlayerInput m_Wrapper;
        public LeftXRControllerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Position => m_Wrapper.m_LeftXRController_Position;
        public InputAction @Rotation => m_Wrapper.m_LeftXRController_Rotation;
        public InputActionMap Get() { return m_Wrapper.m_LeftXRController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LeftXRControllerActions set) { return set.Get(); }
        public void AddCallbacks(ILeftXRControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_LeftXRControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LeftXRControllerActionsCallbackInterfaces.Add(instance);
            @Position.started += instance.OnPosition;
            @Position.performed += instance.OnPosition;
            @Position.canceled += instance.OnPosition;
            @Rotation.started += instance.OnRotation;
            @Rotation.performed += instance.OnRotation;
            @Rotation.canceled += instance.OnRotation;
        }

        private void UnregisterCallbacks(ILeftXRControllerActions instance)
        {
            @Position.started -= instance.OnPosition;
            @Position.performed -= instance.OnPosition;
            @Position.canceled -= instance.OnPosition;
            @Rotation.started -= instance.OnRotation;
            @Rotation.performed -= instance.OnRotation;
            @Rotation.canceled -= instance.OnRotation;
        }

        public void RemoveCallbacks(ILeftXRControllerActions instance)
        {
            if (m_Wrapper.m_LeftXRControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILeftXRControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_LeftXRControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LeftXRControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LeftXRControllerActions @LeftXRController => new LeftXRControllerActions(this);
    public interface IRightXRControllerActions
    {
        void OnPosition(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
    }
    public interface ILeftXRControllerActions
    {
        void OnPosition(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
    }
}
